### ISSUE TITLE
later Hugo versions fail to build

### ISSUE THREAD

**Issue by privatemaker** [tracking-exposed/hugo-theme-trex#5]
as of Hugo v 0.55.0 hugo sites using this theme will not build. I think is due to this issue [deprecated warning](https://discourse.gohugo.io/t/pages-hugo-is-deprecated-as-of-0-55-0/17991). i investigate this now and try to fix.

```
user@localhost:~/facebook.tracking.exposed$ hugo server --bind=0.0.0.0 --port=1314
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/gohugoio/hugo/resources/page.PermalinkExpander.validate(0xc00027b4a0, 0x0, 0xc00027b050, 0x0, 0x0, 0x1)
	/home/user/hugo/resources/page/permalinks.go:154 +0x229
github.com/gohugoio/hugo/resources/page.PermalinkExpander.parse(0xc00027b4a0, 0x0, 0xc00027b050, 0xc00027b4d0, 0xc0002a2728, 0x1086bc0, 0xc00027b440)
	/home/user/hugo/resources/page/permalinks.go:94 +0x356
github.com/gohugoio/hugo/resources/page.NewPermalinkExpander(0xc00027b050, 0x4b, 0x1194711, 0x3, 0x119a051, 0x5)
	/home/user/hugo/resources/page/permalinks.go:66 +0x786
github.com/gohugoio/hugo/resources.NewSpec(0xc00027b050, 0xc00027b0e0, 0xc000203340, 0xc000551100, 0x9, 0x9, 0xc000550a00, 0x11, 0x11, 0x20, ...)
	/home/user/hugo/resources/resource.go:104 +0x144
github.com/gohugoio/hugo/deps.New(0xc000203340, 0xc000031000, 0xc000128310, 0x0, 0x0, 0x13f12a0, 0xc00029d800, 0xc000550a00, 0x11, 0x11, ...)
	/home/user/hugo/deps/deps.go:221 +0x242
github.com/gohugoio/hugo/hugolib.applyDeps(0xc000203340, 0xc000031000, 0x0, 0x0, 0x0, 0x13f12a0, 0xc00029d800, 0x0, 0x0, 0x0, ...)
	/home/user/hugo/hugolib/hugo_sites.go:386 +0x3aa
github.com/gohugoio/hugo/hugolib.newHugoSites(0xc000203340, 0xc000031000, 0x0, 0x0, 0x0, 0x13f12a0, 0xc00029d800, 0x0, 0x0, 0x0, ...)
	/home/user/hugo/hugolib/hugo_sites.go:310 +0x3e2
github.com/gohugoio/hugo/hugolib.NewHugoSites(0xc000203340, 0xc000031000, 0x0, 0x0, 0x0, 0x13f12a0, 0xc00029d800, 0x0, 0x0, 0x0, ...)
	/home/user/hugo/hugolib/hugo_sites.go:420 +0x102
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
	/home/user/hugo/commands/commandeer.go:374 +0x1b6
sync.(*Once).Do(0xc000529d70, 0xc00011d950)
	/usr/local/go/src/sync/once.go:44 +0xb3
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc000447980, 0xc000520101, 0x13dc020, 0xc00000e020)
	/home/user/hugo/commands/commandeer.go:334 +0x6fb
github.com/gohugoio/hugo/commands.newCommandeer(0xc000550101, 0xc00027e680, 0x13db200, 0xc000568f40, 0xc000529b40, 0x0, 0x0, 0x0, 0xc0001f1180, 0x1, ...)
	/home/user/hugo/commands/commandeer.go:160 +0x193
github.com/gohugoio/hugo/commands.initializeConfig(0x101, 0xc00027e680, 0x13db200, 0xc000568f40, 0xc000529b40, 0x0, 0x0, 0xc00011db78)
	/home/user/hugo/commands/hugo.go:125 +0x76
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc000568f40, 0xc000134a00, 0xc000529ac0, 0x0, 0x2, 0x0, 0x0)
	/home/user/hugo/commands/server.go:238 +0x1c7
github.com/gohugoio/hugo/commands.(*serverCmd).server-fm(0xc000134a00, 0xc000529ac0, 0x0, 0x2, 0x0, 0x0)
	/home/user/hugo/commands/server.go:88 +0x52
github.com/spf13/cobra.(*Command).execute(0xc000134a00, 0xc000529a80, 0x2, 0x2, 0xc000134a00, 0xc000529a80)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f0c80, 0xc00055cdc0, 0xc0001885a0, 0x0)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/gohugoio/hugo/commands.Execute(0xc0000300d0, 0x3, 0x3, 0x8, 0xc00011df88, 0x48d3a0, 0xc000080058)
	/home/user/hugo/commands/hugo.go:91 +0xad
main.main()
	/home/user/hugo/main.go:23 +0x6a
```

**Comment by vecna** [comment]
`[[menu = "main" ]]` should become `[[menu]]`
